# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\"\x07\n\x05\x45mpty\"0\n\x0bTermRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"V\n\x11UpdateTermRequest\x12\x14\n\x0c\x63urrent_name\x18\x01 \x01(\t\x12+\n\x0cupdated_term\x18\x02 \x01(\x0b\x32\x15.glossary.TermRequest\"=\n\x0cTermResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"2\n\tTermsList\x12%\n\x05terms\x18\x01 \x03(\x0b\x32\x16.glossary.TermResponse\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xff\x01\n\x0fGlossaryService\x12\x30\n\x08GetTerms\x12\x0f.glossary.Empty\x1a\x13.glossary.TermsList\x12\x38\n\x07\x41\x64\x64Term\x12\x15.glossary.TermRequest\x1a\x16.glossary.TermResponse\x12\x41\n\nUpdateTerm\x12\x1b.glossary.UpdateTermRequest\x1a\x16.glossary.TermResponse\x12=\n\nDeleteTerm\x12\x15.glossary.TermRequest\x1a\x18.glossary.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_TERMREQUEST']._serialized_start=37
  _globals['_TERMREQUEST']._serialized_end=85
  _globals['_UPDATETERMREQUEST']._serialized_start=87
  _globals['_UPDATETERMREQUEST']._serialized_end=173
  _globals['_TERMRESPONSE']._serialized_start=175
  _globals['_TERMRESPONSE']._serialized_end=236
  _globals['_TERMSLIST']._serialized_start=238
  _globals['_TERMSLIST']._serialized_end=288
  _globals['_DELETERESPONSE']._serialized_start=290
  _globals['_DELETERESPONSE']._serialized_end=323
  _globals['_GLOSSARYSERVICE']._serialized_start=326
  _globals['_GLOSSARYSERVICE']._serialized_end=581
# @@protoc_insertion_point(module_scope)
